export const Questions = [
    { question: "What is the full form of HTML?", subject: "HTML" },
    { question: "What is SGML?", subject: "HTML" },
    { question: "Is SGML part of HTML or HTML is part of SGML?", subject: "HTML" },
    { question: "What is Boyler Plate Code?", subject: "HTML" },
    { question: "Write the structure of HTML document.", subject: "HTML" },
    { question: "Define Meta Tag.", subject: "HTML" },
    { question: "Write at least 10 valid Attributes in HTML.", subject: "HTML" },
    { question: "What is Absolute Link and Relative Link?", subject: "HTML" },
    { question: "Is H6 and span tag are of same size?", subject: "HTML" },
    { question: "How you will write H2O and x2 in HTML", subject: "HTML" },
    { question: "What are Void elements? With 2 examples", subject: "HTML" },
    { question: "Difference between p tag and pre tag", subject: "HTML" },
    { question: "What are block and inline elements", subject: "HTML" },
    { question: "Write some Block and Inline Elements", subject: "HTML" },
    { question: "Difference between span tag and p tag", subject: "HTML" },

    { question: "Full form of CSS.", subject: "CSS" },
    { question: "Syntax for writing CSS.", subject: "CSS" },
    { question: "In how many types we can add CSS into HTML document?", subject: "CSS" },
    { question: "Which is of Higher Priority?", subject: "CSS" },
    { question: "What is Box model?", subject: "CSS" },
    { question: "What is Flex Model?", subject: "CSS" },
    { question: "What all Properties Display contains?", subject: "CSS" },
    { question: "What all Properties Position contains?", subject: "CSS" },
    { question: "Difference between Sticky and Fixed...", subject: "CSS" },
    { question: "What is Margin, Padding and Border?", subject: "CSS" },
    { question: "How many types of color systems are There... write with examples...", subject: "CSS" },
    { question: "How many UNITS are there?", subject: "CSS" },
    { question: "How to apply shadow in text? And how to in Div?", subject: "CSS" },
    { question: "What is :HOVER?", subject: "CSS" },
    { question: "How to add Image with CSS… and explain their properties…", subject: "CSS" }
];
